M48
; DRILL file {KiCad 9.0.3-9.0.3-0~ubuntu24.04.1} date 2025-12-01T14:44:47+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-01T14:44:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-9.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X154.8Y-67.0
X154.8Y-94.7
X182.6Y-67.0
X182.6Y-94.8
M30
